pipeline {
    agent any
    environment {
        IMAGE = 'yourdockerhubusername/portfolio:latest'
    }
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/Y0srgh/whoami.dev.git'
            }
        }
        stage('Code Quality') {
            steps {
                sh './scripts/sonar_scan.sh'
            }
        }
        stage('Security Scan') {
            steps {
                sh './scripts/scan_with_trivy.sh'
            }
        }
        stage('Build Image') {
            steps {
                sh 'docker build -t $IMAGE .'
            }
        }
        stage('Push Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                    sh 'echo $PASS | docker login -u $USER --password-stdin'
                    sh 'docker push $IMAGE'
                }
            }
        }
        stage('Deploy to K8s') {
            steps {
                sh 'ansible-playbook ansible/deploy-portfolio.yml'
            }
        }
    }
}